name: Automated API tests using Postman CLI

on: 
  push:
  pull_request: 
  workflow_dispatch: 

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "52509354-ecdf3c4e-f459-430b-89aa-d7809cb5bebe" -e "52509354-7c78c7a8-1a03-40c9-8bae-a79af23d9489"  --report-events
