name: Automated API tests using Postman CLI

on: 
    push:
    pull_request:
    workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI 
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run Spec lint (governance gate)
        run: |
          postman spec lint 4e218718-91fa-41cb-b39c-b98d7d39656e --workspace-id 054afea7-ab5c-471d-98d3-86d2a6cd5234 --report-events
      - name: Run API tests (non-blocking)
        continue-on-error: true
        run: |
          postman collection run "52509354-acfc040b-fd24-4b9c-853a-72caf08c2272" -e "52509354-3b02e674-e6ee-4f70-b446-c78b0fa34042" --report-events
